name: Conditional secret
on:
  push:

jobs:
    with_secret:
        uses: ./.github/workflows/rewo_rewo.yml
        secrets:
            test: ${{ secrets.TEST_SECRET}}

    without_secret:
        uses: ./.github/workflows/rewo_rewo.yml