name: Conditional secret
on:
  push:
    paths:
      - .github/workflows/rewo_rewo.yml
      - .github/workflows/conditional_secret.yaml

jobs:
    with_secret:
        uses: ./.github/workflows/rewo_rewo.yml
        secrets:
            test: ${{ secrets.TEST_SECRET}}

    without_secret:
        uses: ./.github/workflows/rewo_rewo.yml