name: On push with path exclude
on:
  push:
    branches:
      - "main"
    paths:
      - "**"
      - "!to_exclude/**"

jobs:
  start:
    name: Start
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
