on:
  workflow_call:
    inputs:
      foo:
        required: false
        type: string
    secrets:
      test:
        required: false

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - run: echo "foo"
      
      - run: echo "${{ inputs.foo }}"
    
      - name: test conditional secrets
        env:
          test: ${{ secrets.test }}
        if: env.test != ''
        run: echo ${{ env.test}}
